### ISSUE TITLE
copy/paste/move parts of canvas

### ISSUE THREAD

**Issue by jennschiffer** [jennschiffer/make8bitart#31]
but it's gotta stay within the grid

**Comment by tessalt** [comment]
so I have this pretty much working on my fork cause I needed it, and it works well enough for my purposes but I'm not happy enough with it to make a PR. 

https://github.com/tessalt/make8bitart/compare/selectables

Two main issues: UX is weird right now, can't work out how you'd choose whether you want to move or copy (like do you select first and then choose a tool? I'm not sure what people would really expect). 

Second issue is getting undo/redo to work. I'm just using get/put imageData methods so I think I'd have to iterate through the entire imageData array and call `pushToHistory` once for every pixel (or every 15 pixels...) anyways it sounds messy and I need to think about it more.

Anyways, lmk if you want to chat about this sometime!

**Comment by joshturner** [comment]
I think you need a Select tool rather than having Move and Copy tools. Most desktop apps have two tools to accomplish moving: A select tool (Marching Ants) and a Move Tool (usually a black arrow). You make your selection with the select tool and them use the move tool to... well, move the selection.

Photoshop example:
http://cl.ly/233r3S051f0d

Another approach might be to automagically make the users cursor turn into a Move tool once they have hovered over their active selection. 
Example:
http://cl.ly/0y3l0n1Z1a2i

Copy requires a select tool as well but also needs Paste to drop the copied selection into the canvas. These are accessed as Menu items or Keyboard shortcuts.

**Comment by jennschiffer** [comment]
just pushed cut/copy/paste! :space_invader:
