### ISSUE TITLE
Panel Dragging not working in Firefox

### ISSUE THREAD

**Issue by potch** [jennschiffer/make8bitart#54]
Been trying to debug this on my own, but can't figure out what's going on.

The drag handles on panels are not working for me. I've tried latest Firefox all the way up to the current Firefox Nightly and had the same experience. I don't see any JS errors or failed network requests.

Interestingly, though I see "cursor:move" set on the drag handles, I don't see the cursor when I hover them.

**Comment by jennschiffer** [comment]
ugh this is so annoying - so i removed the img from the css selector so the hovering works. i created this branch to start debugging: https://github.com/jennschiffer/make8bitart/tree/debugging-ff-draggy

at this point, i am console.log'ing $this when clicking on the ui-dragger button. in chrome, it has length 1 and img context, but in firefox it says length 0. so that's :cool:

**Comment by jennschiffer** [comment]
NEVER MIND I FIXED IT AND EXPLAINED HERE https://github.com/jennschiffer/make8bitart/pull/55

but that still doesn't make it any less bizarre to me that different browsers get different context when clicking but DIFFERENT FOLKS...
